<?php

declare(strict_types=1);

use MissionGaming\Tactician\DTO\Event;
use MissionGaming\Tactician\DTO\Participant;
use MissionGaming\Tactician\DTO\Result;
use MissionGaming\Tactician\DTO\Schedule;
use MissionGaming\Tactician\Examples\Example;
use MissionGaming\Tactician\Examples\Measured;
use MissionGaming\Tactician\Exceptions\IncompleteScheduleException;
use MissionGaming\Tactician\Exceptions\InvalidConfigurationException;
use MissionGaming\Tactician\Exceptions\SchedulingException;
use MissionGaming\Tactician\Repack\RepackOutcome;
use MissionGaming\Tactician\Repack\ViolationKind;
use MissionGaming\Tactician\Scheduling\RoundRobinScheduler;
use MissionGaming\Tactician\Standings\Standings;
use MissionGaming\Tactician\Tests\Support\ExampleResults;
use MissionGaming\Tactician\Tests\Support\GoldenCases;
use MissionGaming\Tactician\Tests\Support\GoldenText;
use MissionGaming\Tactician\Timeline\ScheduledSchedule;
use PHPUnit\Framework\Assert;

/*
 * Examples are executable documentation and must not ship without
 * validation. Stale examples have shipped fatal errors and false claims
 * before - see the git history for examples 06, 07, 09, 10 and 11.
 *
 * An example computes a named set of results and hands it to
 * Example::present() (examples/support/Example.php), which displays it as a page or as text.
 * The examples are checked on the results, never on the display:
 *
 * 1. Every script in examples/ runs in a PHP process of its own under E_ALL
 *    and must not emit a warning, notice or deprecation.
 * 2. Every example has an entry in $demonstrations below, which asserts on
 *    the objects the example built what the example is there to show. The
 *    assertions are worked out from the schedule, bracket or table itself,
 *    not read back from a number the example reports.
 * 3. tests/Feature/GoldenOutputTest.php pins the whole result set as text
 *    (tests/Fixtures/golden/examples/, regenerated by `composer golden-update`).
 *
 * A new script without an entry here, without a fixture, or missing from
 * examples/README.md and examples/index.php fails the suite.
 *
 * A value that cannot be the same on every run is wrapped in Measured by the
 * example, with the reason. Its fixture line is the unit and the reason, and
 * the example's entry here checks the value itself (example 12).
 *
 * How results are drawn is tested once, in tests/Feature/ExampleRendererTest.php.
 */

$root = dirname(__DIR__, 2);
$exampleScripts = glob($root . '/examples/*.php') ?: [];

/**
 * A named result of an example, checked to be of the expected class.
 *
 * @template T of object
 *
 * @param array<string, mixed> $results
 * @param class-string<T> $class
 * @return T
 *
 * @throws PHPUnit\Framework\Exception
 * @throws PHPUnit\Framework\ExpectationFailedException When the result is missing or of another class
 */
function exampleResult(array $results, string $name, string $class): object
{
    Assert::assertArrayHasKey($name, $results, "The example no longer presents a result named '{$name}'");
    Assert::assertInstanceOf($class, $results[$name], "The result '{$name}' is not a {$class}");

    return $results[$name];
}

/**
 * A named result of an example that is an array.
 *
 * @param array<string, mixed> $results
 * @return array<array-key, mixed>
 *
 * @throws PHPUnit\Framework\Exception
 * @throws PHPUnit\Framework\ExpectationFailedException When the result is missing or not an array
 */
function exampleArray(array $results, string $name): array
{
    Assert::assertArrayHasKey($name, $results, "The example no longer presents a result named '{$name}'");
    Assert::assertIsArray($results[$name], "The result '{$name}' is not an array");

    return $results[$name];
}

/**
 * The ids of an event's participants, sorted, joined by `|`: the same key
 * whichever participant is named first.
 */
function examplePair(Event $event): string
{
    $ids = array_map(static fn (Participant $participant): string => $participant->getId(), $event->getParticipants());
    sort($ids);

    return implode('|', $ids);
}

/**
 * The rounds in which each pair meets, by pair key.
 *
 * @param iterable<Event> $events
 * @return array<string, list<int>>
 */
function exampleMeetings(iterable $events): array
{
    $meetings = [];
    foreach ($events as $event) {
        $meetings[examplePair($event)][] = (int) $event->getRound()?->getNumber();
    }

    return $meetings;
}

/**
 * Assert that a schedule is a complete round robin: every pair of the field
 * meets once in every leg, and nobody plays twice in a round.
 *
 * @throws PHPUnit\Framework\Exception
 * @throws PHPUnit\Framework\ExpectationFailedException When it is not
 */
function assertExampleRoundRobin(Schedule $schedule, int $fieldSize, int $legs = 1): void
{
    $meetings = exampleMeetings($schedule);
    $roundsPerLeg = $fieldSize % 2 === 0 ? $fieldSize - 1 : $fieldSize;

    Assert::assertCount(array_sum(range(1, $fieldSize - 1)), $meetings, 'Not every pair of the field meets');
    foreach ($meetings as $pair => $rounds) {
        Assert::assertCount($legs, $rounds, "{$pair} does not meet once per leg");

        // The meeting in leg k falls within that leg's rounds
        foreach ($rounds as $leg => $round) {
            Assert::assertGreaterThan($leg * $roundsPerLeg, $round, "{$pair} meets twice in one leg");
            Assert::assertLessThanOrEqual(($leg + 1) * $roundsPerLeg, $round, "{$pair} misses a leg");
        }
    }

    foreach ($schedule->getEventsByRound() as $round => $events) {
        $playing = [];
        foreach ($events as $event) {
            foreach ($event->getParticipants() as $participant) {
                $playing[] = $participant->getId();
            }
        }
        Assert::assertSame(array_unique($playing), $playing, "A participant plays twice in round {$round}");
    }
}

/**
 * What each example exists to demonstrate, asserted on its results.
 *
 * @var array<string, Closure(array<string, mixed>): void> $demonstrations
 */
$demonstrations = [
    // Four participants: every pair meets once, everyone plays in each of the 3 rounds
    '01-basic-round-robin' => function (array $results): void {
        $schedule = exampleResult($results, 'Schedule', Schedule::class);

        assertExampleRoundRobin($schedule, 4);
        expect(count($schedule))->toBe(6)
            ->and(array_map(count(...), $schedule->getEventsByRound()))->toBe([1 => 2, 2 => 2, 3 => 2])
            ->and(exampleArray($results, 'Participants'))->toHaveCount(4)
            ->and($results['Shape'])->toBe(['Events' => 6, 'Rounds' => 3, 'Participants' => 4, 'Legs' => 1, 'Algorithm' => 'round-robin']);
    },

    // Seeds and metadata are carried by the participants and come back out of the schedule's events
    '02-participants-and-metadata' => function (array $results): void {
        $schedule = exampleResult($results, 'Schedule', Schedule::class);
        $participants = exampleArray($results, 'Participants');

        expect($participants)->toHaveCount(6)
            ->and(array_map(static fn (Participant $participant): ?int => $participant->getSeed(), $participants))->toBe([1, 2, 3, 4, 5, 6]);

        // A schedule without events would pass the loop below untested
        assertExampleRoundRobin($schedule, 6);

        foreach ($schedule as $event) {
            foreach ($event->getParticipants() as $participant) {
                expect($participants)->toContain($participant)
                    ->and($participant->hasMetadata('city'))->toBeTrue();
            }
        }

        expect($results['Reading the first participant'])->toBe([
            'getId()' => 'celtic',
            'getLabel()' => 'Celtic FC',
            'getSeed()' => 1,
            "getMetadataValue('city')" => 'Glasgow',
            "hasMetadata('stadium')" => false,
            "getMetadataValue('stadium', 'unknown')" => 'unknown',
        ])->and(exampleArray($results, 'Labels by country')['Spain'] ?? null)->toBe(['Athletic Bilbao', 'Rayo Vallecano']);

        $cities = [];
        foreach ($participants as $participant) {
            $cities[$participant->getLabel()] = $participant->getMetadataValue('city');
        }
        $openingRound = exampleArray($results, 'Opening round, with cities from the metadata');
        expect($openingRound)->toHaveCount(3);
        foreach ($openingRound as $row) {
            expect($row['City'])->toBe($cities[$row['First named']])
                ->and($row['Their city'])->toBe($cities[$row['Second named']]);
        }
    },

    // Every way of reading a schedule sees the same events; an odd field gives each participant one bye
    '03-iterating-schedules' => function (array $results): void {
        $schedule = exampleResult($results, 'Schedule', Schedule::class);
        $events = $schedule->getEvents();

        assertExampleRoundRobin($schedule, 5);
        expect($results['Events seen by foreach'])->toBe(10)
            ->and($results['count($schedule)'])->toBe(10)
            ->and($results['First event'])->toBe($events[0])
            ->and($results['Last event'])->toBe($events[9])
            ->and($results['Round 3 only'])->toBe($schedule->getEventsByRound()[3])
            ->and($results['Number of events in each round'])->toBe(['Round 1' => 2, 'Round 2' => 2, 'Round 3' => 2, 'Round 4' => 2, 'Round 5' => 2]);

        $byes = exampleArray($results, 'Bye in each round');
        $sorted = array_values($byes);
        sort($sorted);
        expect($sorted)->toBe(['athletic', 'celtic', 'livorno', 'redstar', 'stpauli']);

        // Whoever has the bye does not play in that round
        foreach ($schedule->getEventsByRound() as $round => $roundEvents) {
            foreach ($roundEvents as $event) {
                expect(examplePair($event))->not->toContain((string) $byes['Round ' . $round]);
            }
        }
    },

    // The custom constraint keeps seeds 1 and 6 apart in rounds 1 and 2, and the schedule stays complete
    '04-basic-constraints' => function (array $results): void {
        $unconstrained = exampleResult($results, 'Schedule without constraints', Schedule::class);
        $withNoRepeats = exampleResult($results, 'Schedule with noRepeatPairings() only', Schedule::class);
        $constrained = exampleResult($results, 'Schedule with the custom constraint', Schedule::class);

        assertExampleRoundRobin($unconstrained, 6);
        assertExampleRoundRobin($constrained, 6);

        // Seed 1 is celtic and seed 6 is clapton. Without the constraint they open the season
        $forbidden = 'celtic|clapton';
        expect(exampleMeetings($unconstrained)[$forbidden])->toBe([1]);

        foreach ($constrained as $event) {
            if ($event->getRound()?->getNumber() <= 2) {
                expect(examplePair($event))->not->toBe($forbidden);
            }
        }
        expect(exampleMeetings($constrained)[$forbidden][0])->toBeGreaterThan(2);

        // noRepeatPairings() changes nothing in a round robin, as the example says
        expect(GoldenText::schedule($withNoRepeats))->toBe(GoldenText::schedule($unconstrained))
            ->and($results['Constraints in the set'])->toBe(['No Repeat Pairings', 'Seeds 1 and 6 apart in rounds 1 and 2']);
    },

    // The top two seeds meet after the protected window, and a window the schedule already respects changes nothing
    '05-seed-protection' => function (array $results): void {
        $unprotected = exampleResult($results, 'Schedule without protection', Schedule::class);
        $quarter = exampleResult($results, 'Schedule protected for 25% of the rounds', Schedule::class);
        $half = exampleResult($results, 'Schedule protected for 50% of the rounds', Schedule::class);

        foreach ([$unprotected, $quarter, $half] as $schedule) {
            assertExampleRoundRobin($schedule, 8);
        }

        $topSeeds = 'athletic|celtic';
        expect(exampleMeetings($unprotected)[$topSeeds])->toBe([2])
            ->and(GoldenText::schedule($quarter))->toBe(GoldenText::schedule($unprotected))
            ->and(exampleMeetings($half)[$topSeeds][0])->toBeGreaterThan(3);
    },

    // Over two legs every pair meets again at least 5 rounds later; asking for 6 fails loudly
    '06-rest-periods' => function (array $results): void {
        $schedule = exampleResult($results, 'Two legs with at least 5 rounds between meetings', Schedule::class);
        $failure = exampleResult($results, 'Asking for at least 6 rounds', IncompleteScheduleException::class);

        assertExampleRoundRobin($schedule, 6, 2);
        foreach (exampleMeetings($schedule) as $pair => $rounds) {
            expect($rounds[1] - $rounds[0])->toBeGreaterThanOrEqual(5, $pair);
        }

        expect($failure->getExpectedEventCount())->toBe(30)
            ->and($failure->getActualEventCount())->toBeLessThan(30);
    },

    // A metadata rule that forbids pairings makes a complete round robin impossible, and the failure names them
    '07-metadata-constraints' => function (array $results): void {
        $capped = exampleResult($results, 'At most two regions per event: schedule', Schedule::class);
        $platform = exampleResult($results, 'Same platform only', IncompleteScheduleException::class);
        $timezone = exampleResult($results, 'UTC offsets within 6 hours only', IncompleteScheduleException::class);

        assertExampleRoundRobin($capped, 6);

        // Two regions at most always holds for two participants: as the example says, the schedule is the unconstrained one
        $unconstrained = (new RoundRobinScheduler())->schedule(exampleArray($results, 'Participants'));
        expect(GoldenText::schedule($capped))->toBe(GoldenText::schedule($unconstrained));

        // Four PC participants and two on Console: 8 cross-platform pairings
        $blocked = exampleArray($results, 'Pairings the platform rule blocks');
        expect($blocked)->toHaveCount(8);
        foreach ($blocked as $pairing) {
            expect($pairing)->toContain('blocked by: Same platform');
        }

        expect($platform->getActualEventCount())->toBeLessThan(15)
            ->and($timezone->getActualEventCount())->toBeLessThan(15)
            ->and($timezone->getExpectedEventCount())->toBe(15);
    },

    // A round-dependent custom rule moves a pairing; a rule that forbids pairings outright fails and is named
    '08-custom-constraints' => function (array $results): void {
        $schedule = exampleResult($results, 'Schedule with the veterans apart in rounds 1 to 3', Schedule::class);
        $failure = exampleResult($results, 'Budget tier separation', IncompleteScheduleException::class);

        assertExampleRoundRobin($schedule, 6);

        // The veterans are dragons and hawks
        expect(exampleMeetings($schedule)['dragons|hawks'][0])->toBeGreaterThan(3)
            ->and($results['Round in which the two veterans meet'])->toBe(['Without constraints' => 3, 'With the closure constraint' => exampleMeetings($schedule)['dragons|hawks'][0]]);

        // high v low: dragons and wolves against hawks and lions
        $blocked = exampleArray($results, 'Pairings the budget rule blocks');
        expect($blocked)->toHaveCount(4)
            ->and($failure->getActualEventCount())->toBeLessThan(15);
        foreach ($blocked as $pairing) {
            expect($pairing)->toContain('blocked by: Budget tier separation');
        }
    },

    // Each pair meets once per leg; mirrored legs swap the roles, repeated legs keep them
    '09-multi-leg-home-away' => function (array $results): void {
        $mirrored = exampleResult($results, 'Mirrored legs', Schedule::class);
        $repeated = exampleResult($results, 'Repeated legs', Schedule::class);
        $shuffled = exampleResult($results, 'Shuffled legs (seed 2026)', Schedule::class);

        // For each pairing, whether its second meeting has the roles of the
        // first swapped. The meetings are matched by pairing, so the order of
        // the events inside a round plays no part.
        $swapped = static function (Schedule $schedule): array {
            $firstNamed = [];
            foreach ($schedule as $event) {
                $firstNamed[examplePair($event)][] = $event->getParticipants()[0]->getId();
            }
            ksort($firstNamed);

            return array_map(static fn (array $homes): bool => $homes[0] !== $homes[1], $firstNamed);
        };

        // How often each participant is first-named, by label, as the example reports it
        $homeGames = static function (Schedule $schedule): array {
            $count = [];
            foreach ($schedule as $event) {
                foreach ($event->getParticipants() as $position => $participant) {
                    $count[$participant->getLabel()] = ($count[$participant->getLabel()] ?? 0) + ($position === 0 ? 1 : 0);
                }
            }
            ksort($count);

            return $count;
        };

        foreach ([$mirrored, $repeated, $shuffled] as $schedule) {
            assertExampleRoundRobin($schedule, 4, 2);
            expect(count($schedule))->toBe(12);

            // Each pairing returns exactly one leg (3 rounds) after its first meeting
            foreach (exampleMeetings($schedule) as $pair => $rounds) {
                expect($rounds[1] - $rounds[0])->toBe(3, $pair);
            }
        }

        // Mirrored legs swap every pairing, repeated legs swap none, and the
        // seeded shuffle swaps some: it is neither of the other two
        expect(array_count_values(array_map(intval(...), $swapped($mirrored))))->toBe([1 => 6])
            ->and(array_count_values(array_map(intval(...), $swapped($repeated))))->toBe([0 => 6])
            ->and(array_unique(array_values($swapped($shuffled))))->toHaveCount(2);

        // The home counts the example reports are the ones the schedules hold
        expect($results['Home games per club, mirrored legs'])->toBe(['Arsenal' => 3, 'Chelsea' => 3, 'Liverpool' => 3, 'Manchester City' => 3])
            ->and($results['Home games per club, mirrored legs'])->toBe($homeGames($mirrored))
            ->and($results['Home games per club, repeated legs'])->toBe($homeGames($repeated))
            ->and($results['Home games per club, shuffled legs'])->toBe($homeGames($shuffled))
            ->and($homeGames($shuffled))->not->toBe($homeGames($mirrored))
            ->and($homeGames($shuffled))->not->toBe($homeGames($repeated));
    },

    // All the constraints hold at once in a complete two-leg season; seed protection and the tier rule moved fixtures
    '10-complex-tournament' => function (array $results): void {
        $schedule = exampleResult($results, 'Schedule with the constraints', Schedule::class);

        assertExampleRoundRobin($schedule, 8, 2);

        $tier = ['fnatic' => 'S', 'tsm' => 'S', 't1' => 'S', 'g2' => 'A', 'cloud9' => 'A', 'geng' => 'A', 'mad' => 'B', 'thieves' => 'B'];
        foreach ($schedule as $event) {
            if ($event->getRound()?->getNumber() > 2) {
                continue;
            }
            $tiers = array_map(static fn (Participant $participant): string => $tier[$participant->getId()], $event->getParticipants());
            sort($tiers);

            expect(examplePair($event))->not->toBe('fnatic|tsm')
                ->and($tiers)->not->toBe(['B', 'S']);
        }
        $gaps = [];
        $mismatchRounds = [];
        foreach (exampleMeetings($schedule) as $pair => $rounds) {
            expect($rounds[1] - $rounds[0])->toBeGreaterThanOrEqual(7, $pair);
            $gaps[] = $rounds[1] - $rounds[0];

            [$first, $second] = explode('|', $pair);
            if ([$tier[$first], $tier[$second]] === ['S', 'B'] || [$tier[$first], $tier[$second]] === ['B', 'S']) {
                array_push($mismatchRounds, ...$rounds);
            }
        }

        if ($gaps === [] || $mismatchRounds === []) {
            Assert::fail('The schedule holds no pairing, or no S-tier against B-tier pairing, to check.');
        }

        // The summary the example reports for a schedule is the one worked out here from the schedule itself,
        // which is what makes its summary of the unconstrained season, read below, worth reading
        expect($results['With the constraints'])->toBe([
            'Events' => count($schedule),
            'Rounds' => 14,
            'Rounds in which seeds 1 and 2 meet' => implode(' and ', exampleMeetings($schedule)['fnatic|tsm']),
            'Earliest round with S-tier against B-tier' => min($mismatchRounds),
            'Fewest rounds between the two meetings of a pair' => min($gaps),
        ]);

        // Without the constraints seed protection and the tier rule are both broken, so those two are what
        // moved the fixtures. The gap between meetings is 7 either way: two mirrored legs already give it,
        // and noRepeatPairings() changes nothing in a round robin (example 04).
        $without = exampleArray($results, 'Without constraints');
        expect($without['Rounds in which seeds 1 and 2 meet'])->toBe('2 and 9')
            ->and($without['Earliest round with S-tier against B-tier'])->toBe(1)
            ->and($without['Fewest rounds between the two meetings of a pair'])->toBe(7)
            ->and($results['Constraints in the set'])->toBe(4);
    },

    // The two exceptions are thrown for the reasons given and carry what the example reads from them
    '11-error-handling' => function (array $results): void {
        $invalid = exampleResult($results, 'Duplicate participant ids', InvalidConfigurationException::class);
        $incomplete = exampleResult($results, 'A constraint that rejects everything', IncompleteScheduleException::class);

        expect($invalid)->toBeInstanceOf(SchedulingException::class)
            ->and($incomplete)->toBeInstanceOf(SchedulingException::class)
            ->and($results['The issue it names'])->toBe('All participants must have unique IDs')
            ->and($results['How far generation got'])->toBe(['Expected events' => 6, 'Generated events' => 0, 'Missing events' => 6])
            ->and($results['Diagnostic report'])->toBeString()->toContain('Reject everything')
            ->and($results['Class caught as SchedulingException'])->toBe(IncompleteScheduleException::class);

        assertExampleRoundRobin(exampleResult($results, 'A valid request', Schedule::class), 4);
    },

    // The counts are exact; the durations are measured, say why, and are checked for being durations
    '12-performance-patterns' => function (array $results): void {
        $generation = exampleArray($results, 'Generating a single-leg round robin');
        expect(array_keys($generation))->toBe(['6 participants', '12 participants', '20 participants', '30 participants']);

        foreach ([6, 12, 20, 30] as $size) {
            $row = $generation[$size . ' participants'];
            expect($row['Events'])->toBe(intdiv($size * ($size - 1), 2))
                ->and($row['Rounds'])->toBe($size - 1)
                ->and($row['Generated in'])->toBeInstanceOf(Measured::class);
        }

        $reading = exampleArray($results, 'Reading the 30-participant schedule');
        expect(array_keys($reading))->toBe(['foreach', 'getEvents()', 'count()']);
        foreach ($reading as $way) {
            expect($way['Events seen'])->toBe(435)
                ->and($way['Took'])->toBeInstanceOf(Measured::class);
        }

        $measured = [];
        array_walk_recursive($results, static function (mixed $value) use (&$measured): void {
            if ($value instanceof Measured) {
                $measured[] = $value;
            }
        });
        expect($measured)->toHaveCount(7);
        foreach ($measured as $value) {
            expect($value->unit)->toBe('ms')
                ->and($value->value)->toBeFloat()->toBeGreaterThanOrEqual(0.0)->toBeLessThan(60_000.0)
                ->and($value->reason)->toContain('differs on every run');
        }
    },

    // Three Swiss rounds: nobody meets twice, and after round 1 players on the same score meet
    '13-swiss-stage-engine' => function (array $results): void {
        $rounds = exampleArray($results, 'Rounds as played');
        $standings = exampleResult($results, 'Final standings', Standings::class);

        expect(array_keys($rounds))->toBe(['Round 1', 'Round 2', 'Round 3']);

        $met = [];
        $wins = [];
        foreach ($rounds as $played) {
            expect($played)->toHaveCount(4);

            $playing = [];
            foreach ($played as $result) {
                assert($result instanceof Result);
                [$first, $second] = $result->getEvent()->getParticipants();
                $playing[] = $first->getId();
                $playing[] = $second->getId();

                // Paired on equal scores: the wins so far are the same
                expect($wins[$first->getId()] ?? 0)->toBe($wins[$second->getId()] ?? 0);
                $met[] = examplePair($result->getEvent());
            }
            expect(array_unique($playing))->toHaveCount(8);

            foreach ($played as $result) {
                assert($result instanceof Result);
                $winner = $result->getWinner()?->getId();
                $wins[(string) $winner] = ($wins[(string) $winner] ?? 0) + 1;
            }
        }
        expect(array_unique($met))->toHaveCount(12);

        $values = array_map(static fn ($entry): float => $entry->getRankingValue(), $standings->getEntries());
        $sorted = $values;
        rsort($sorted);
        expect($values)->toBe($sorted)
            ->and($standings->getEntries()[0]->getParticipant()->getId())->toBe('magnus')
            ->and($standings->getEntries()[0]->getWins())->toBe(3)
            ->and($results['Outcome'])->toBe(['Last round played' => 3, 'Results recorded' => 12]);
    },

    // The top two of each pool qualify, winners first, and the bracket's last winner is the champion
    '14-groups-to-knockout' => function (array $results): void {
        $tables = exampleArray($results, 'Pool tables');
        $qualifiers = exampleArray($results, 'Qualifiers, in knockout seeding order');
        $knockout = exampleArray($results, 'Knockout');

        expect(array_keys($tables))->toBe(['Pool A', 'Pool B']);
        $ranked = [];
        foreach ($tables as $pool => $table) {
            assert($table instanceof Standings);
            expect($table->getEntries())->toHaveCount(4);
            $ranked[$pool] = array_map(static fn ($entry): Participant => $entry->getParticipant(), $table->getEntries());
        }

        expect($qualifiers)->toBe([$ranked['Pool A'][0], $ranked['Pool B'][0], $ranked['Pool A'][1], $ranked['Pool B'][1]])
            ->and(array_keys($knockout))->toBe(['Semifinal', 'Final'])
            ->and($knockout['Semifinal'])->toHaveCount(2)
            ->and($knockout['Final'])->toHaveCount(1);

        $semifinalWinners = array_map(static fn (Result $result): ?Participant => $result->getWinner(), $knockout['Semifinal']);
        $final = $knockout['Final'][0];
        assert($final instanceof Result);

        $ids = static function (array $participants): array {
            $ids = array_map(static fn (?Participant $participant): ?string => $participant?->getId(), $participants);
            sort($ids);

            return $ids;
        };

        // The finalists are the two semifinal winners, whichever of them is named first
        expect($ids($final->getEvent()->getParticipants()))->toBe($ids($semifinalWinners))
            ->and($semifinalWinners)->not->toContain(null)
            ->and($results['Champion'])->toBe($final->getWinner())
            ->and($final->getWinner()?->getId())->toBe('bra');
    },

    // Weekly rounds at two kickoff times on two pitches, with the rest rule and the blackout respected
    '15-timeline-assignment' => function (array $results): void {
        $scheduled = exampleResult($results, 'Season calendar', ScheduledSchedule::class);
        $blackoutFrom = new DateTimeImmutable('2026-08-31 00:00:00', new DateTimeZone('Europe/London'));
        $blackoutTo = new DateTimeImmutable('2026-09-01 00:00:00', new DateTimeZone('Europe/London'));

        expect(count($scheduled))->toBe(30);

        $taken = [];
        $kickoffsByParticipant = [];
        foreach ($scheduled->getEventsByRound() as $round => $events) {
            $matchDay = (new DateTimeImmutable('2026-08-01', new DateTimeZone('UTC')))->modify('+' . (($round - 1) * 7) . ' days');

            foreach ($events as $event) {
                $kickoff = $event->getKickoff();

                // 18:00 and 20:00 in London during summer time
                expect($kickoff->format('Y-m-d'))->toBe($matchDay->format('Y-m-d'))
                    ->and(gmdate('H:i', $kickoff->getTimestamp()))->toBeIn(['17:00', '19:00'])
                    ->and($event->getResource())->toBeIn(['North Pitch', 'South Pitch'])
                    ->and($kickoff >= $blackoutFrom && $kickoff < $blackoutTo)->toBeFalse();

                $taken[] = $kickoff->getTimestamp() . ' ' . $event->getResource();
                foreach ($event->getEvent()->getParticipants() as $participant) {
                    $kickoffsByParticipant[$participant->getId()][] = $kickoff->getTimestamp();
                }
            }
        }

        // No pitch is used twice at one time, and everybody has at least 48 hours between kickoffs
        expect(array_unique($taken))->toHaveCount(30);
        foreach ($kickoffsByParticipant as $participant => $kickoffs) {
            sort($kickoffs);
            expect($kickoffs)->toHaveCount(10);
            for ($index = 1; $index < count($kickoffs); ++$index) {
                expect($kickoffs[$index] - $kickoffs[$index - 1])->toBeGreaterThanOrEqual(48 * 3600, $participant);
            }
        }

        expect($results['Scheduled events restored from JSON'])->toBe(30)
            ->and($results['First kickoff of the final round'])->toEqual(new DateTimeImmutable('2026-10-03 17:00:00', new DateTimeZone('UTC')));
    },

    // The default generator fails, backtracking finds a schedule that honours the policy, and no solution still fails
    '16-backtracking-generation' => function (array $results): void {
        exampleResult($results, 'Default generation', IncompleteScheduleException::class);
        $schedule = exampleResult($results, 'Backtracking generation', Schedule::class);
        $unsatisfiable = exampleResult($results, 'A constraint that rejects everything, with backtracking', IncompleteScheduleException::class);

        assertExampleRoundRobin($schedule, 4);

        $meetings = exampleMeetings($schedule);
        expect($meetings['cit|unt'])->toBe([1])
            ->and($meetings['ath|unt'])->toBe([2])
            ->and($meetings['unt|wan'])->toBe([3])
            ->and($unsatisfiable->getMessage())->toContain('unsatisfiable')
            ->and(exampleArray($results, 'Blocked pairings it names'))->toHaveCount(6);
    },

    // The best of 25 samples scores lower than the first sample alone, and the score is the weighted sum
    '17-schedule-optimization' => function (array $results): void {
        $scores = [];
        foreach (exampleArray($results, 'Scores (lower is better)') as $row) {
            $scores[$row['Metric']] = $row;
        }

        expect(array_keys($scores))->toBe(['Role Balance', 'Role Streaks', 'Pairing Spacing', 'Weighted score'])
            ->and($scores['Weighted score']['Best of 25'])->toBeLessThan($scores['Weighted score']['First sample']);

        foreach (['First sample', 'Best of 25'] as $column) {
            expect($scores['Weighted score'][$column])->toEqualWithDelta(
                3.0 * $scores['Role Balance'][$column] + 2.0 * $scores['Role Streaks'][$column] + $scores['Pairing Spacing'][$column],
                1e-9
            );
        }

        expect($results['Sampling'])->toBe(['Candidates generated' => 25, 'Candidates that failed' => 0]);
        assertExampleRoundRobin(exampleResult($results, 'The schedule kept', Schedule::class), 6, 2);
    },

    // One step per request, the state growing in storage, and a complete table at the end
    '18-stateless-web-flow' => function (array $results): void {
        $requests = exampleArray($results, 'Requests');
        $standings = exampleResult($results, 'Final standings, read by the last request', Standings::class);

        expect(array_column($requests, 'Request'))->toBe([1, 2, 3, 4])
            ->and(array_column($requests, 'Events'))->toBe([0, 3, 3, 3])
            ->and(array_column($requests, 'Did'))->toBe([
                'opened the stage',
                'paired and recorded round 1',
                'paired and recorded round 2',
                'paired and recorded round 3',
            ]);

        $stored = array_column($requests, 'State stored (bytes)');
        $ascending = $stored;
        sort($ascending);
        expect($stored)->toBe($ascending)
            ->and(array_unique($stored))->toHaveCount(4);

        // Three rounds of three events: 9 results, each one a win and a loss
        expect($standings->getEntries())->toHaveCount(6)
            ->and(array_sum(array_map(static fn ($entry): int => $entry->getWins(), $standings->getEntries())))->toBe(9)
            ->and(array_map(static fn ($entry): int => $entry->getPlayed(), $standings->getEntries()))->toBe([3, 3, 3, 3, 3, 3])
            ->and($standings->getEntries()[0]->getParticipant()->getId())->toBe('ana');
    },

    // Every movable event is placed, nobody is double-booked, play is back to back, and only late starts remain
    '19-repacking-a-season' => function (array $results): void {
        $outcome = exampleResult($results, 'Repacked schedule', RepackOutcome::class);
        $fixtures = exampleArray($results, 'Fixtures by event id');

        expect($fixtures)->toHaveCount(12)
            ->and($outcome->getUnplaced())->toBe([])
            ->and(array_map(static fn ($assignment): string => $assignment->getEventId(), $outcome->getAssignments()))
            ->toBe(['e03', 'e04', 'e05', 'e06', 'e07', 'e08', 'e09', 'e10', 'e11', 'e12']);

        // The two pins sit at session 0, slot 0
        $positions = ['e01' => [0, 0], 'e02' => [0, 0]];
        foreach ($outcome->getAssignments() as $assignment) {
            $positions[$assignment->getEventId()] = [$assignment->getSession(), $assignment->getSlot()];
        }

        $perSlot = [];
        $slotsByParticipant = [];
        foreach ($positions as $eventId => [$session, $slot]) {
            // Session 0 has 3 slots, session 1 has 4
            expect($slot)->toBeLessThan($session === 0 ? 3 : 4);

            $perSlot["{$session}/{$slot}"] = ($perSlot["{$session}/{$slot}"] ?? 0) + 1;
            foreach (explode(' v ', (string) $fixtures[$eventId]) as $label) {
                $slotsByParticipant[$label][$session][] = $slot;
            }
        }
        expect(max($perSlot))->toBeLessThanOrEqual(3);

        foreach ($slotsByParticipant as $label => $sessions) {
            foreach ($sessions as $session => $slots) {
                sort($slots);

                // No slot twice (double-booked), no gap (back to back)
                expect($slots)->toBe(range($slots[0], $slots[0] + count($slots) - 1), "{$label} in session {$session}");
            }
        }

        expect($outcome->getViolations())->toHaveCount(4)
            ->and($outcome->getViolationsOfKind(ViolationKind::LateStart))->toHaveCount(4)
            ->and($results['Clean'])->toBeFalse();
    },

    // Out after the second loss: the champion lost once, everybody else twice, and the final was reset
    '20-double-elimination' => function (array $results): void {
        $rounds = exampleArray($results, 'Rounds as played');
        $standings = exampleResult($results, 'Final standings', Standings::class);
        $champion = exampleResult($results, 'Champion', Participant::class);

        expect(array_keys($rounds))->toBe([
            'Round 1: winners round 1',
            'Round 2: losers round 1',
            'Round 3: winners final',
            'Round 4: losers final',
            'Round 5: grand final',
            'Round 6: grand final reset',
        ]);

        $losses = [];
        $played = 0;
        foreach ($rounds as $roundResults) {
            foreach ($roundResults as $result) {
                assert($result instanceof Result);
                ++$played;
                foreach ($result->getEvent()->getParticipants() as $participant) {
                    // Nobody plays on after a second loss
                    expect($losses[$participant->getId()] ?? 0)->toBeLessThan(2);
                    if ($result->getWinner() !== $participant) {
                        $losses[$participant->getId()] = ($losses[$participant->getId()] ?? 0) + 1;
                    }
                }
            }
        }

        // The top seed lost its opening match and still took the title
        $opening = $rounds['Round 1: winners round 1'][0];
        assert($opening instanceof Result);
        expect($opening->getWinner()?->getId())->toBe('ding')
            ->and($champion->getId())->toBe('magnus')
            ->and($losses)->toEqualCanonicalizing(['magnus' => 1, 'hikaru' => 2, 'fabiano' => 2, 'ding' => 2])
            ->and($played)->toBe(7)
            ->and($standings->getEntries()[0]->getParticipant())->toBe($champion)
            ->and($results['Losses'])->toBe(['Magnus' => 1, 'Hikaru' => 2, 'Ding' => 2, 'Fabiano' => 2]);
    },

    // Two participants tie on points; the tiebreaker chain orders them the other way round from score difference
    '21-standings-and-tiebreakers' => function (array $results): void {
        $plain = exampleResult($results, 'Table without tiebreakers', Standings::class);
        $chain = exampleResult($results, 'Table with the tiebreaker chain', Standings::class);
        $ids = static fn (Standings $standings): array => array_map(
            static fn ($entry): string => $entry->getParticipant()->getId(),
            $standings->getEntries()
        );

        expect(exampleArray($results, 'Results'))->toHaveCount(6)
            ->and($ids($plain))->toBe(['boca', 'ajax', 'celtic', 'dynamo'])
            ->and($ids($chain))->toBe(['ajax', 'boca', 'celtic', 'dynamo']);

        [$ajax, $boca] = $chain->getEntries();
        expect($ajax->getRankingValue())->toBe(6.0)
            ->and($boca->getRankingValue())->toBe(6.0)
            // Score difference alone favours Boca Juniors
            ->and($boca->getScoreDifference())->toBeGreaterThan($ajax->getScoreDifference())
            // The first two tiebreakers cannot separate them, the third can
            ->and($ajax->getTiebreakerValue('wins'))->toBe($boca->getTiebreakerValue('wins'))
            ->and($ajax->getTiebreakerValue('buchholz'))->toBe($boca->getTiebreakerValue('buchholz'))
            ->and($ajax->getTiebreakers()['sonneborn-berger'])->toBeGreaterThan($boca->getTiebreakers()['sonneborn-berger'])
            ->and(array_keys($ajax->getTiebreakers()))->toBe(['wins', 'buchholz', 'sonneborn-berger'])
            ->and($plain->getEntries()[0]->getTiebreakers())->toBe([]);
    },
];

/**
 * Run a PHP script in a process of its own and return its exit code and
 * everything it printed, with standard error folded in.
 *
 * @param list<string> $settings `-d` settings, as `name=value`
 * @param array<string, string>|null $environment The whole environment, or null to inherit
 * @return array{int, string}
 *
 * @throws PHPUnit\Framework\AssertionFailedError When the process cannot be started
 */
function runExampleScript(string $script, array $settings, ?string $workingDirectory = null, ?array $environment = null): array
{
    $captured = tempnam(sys_get_temp_dir(), 'example');
    if ($captured === false) {
        Assert::fail('Could not create a temporary file in ' . sys_get_temp_dir());
    }

    $command = [PHP_BINARY];
    foreach ($settings as $setting) {
        $command[] = '-d';
        $command[] = $setting;
    }
    $command[] = $script;

    // Both streams append to one file, so they interleave as they were written
    $process = proc_open(
        $command,
        [1 => ['file', $captured, 'a'], 2 => ['file', $captured, 'a']],
        $pipes,
        $workingDirectory,
        $environment
    );
    if ($process === false) {
        unlink($captured);
        Assert::fail('Could not start PHP to run ' . basename($script));
    }

    $exitCode = proc_close($process);
    $output = (string) file_get_contents($captured);
    unlink($captured);

    return [$exitCode, $output];
}

it('discovers the example scripts', function () use ($exampleScripts): void {
    // index.php and the numbered examples
    expect(count($exampleScripts))->toBe(count(ExampleResults::names()) + 1)
        ->and(count(ExampleResults::names()))->toBeGreaterThanOrEqual(21);
});

it('runs cleanly under full error reporting', function (string $script): void {
    [$exitCode, $output] = runExampleScript($script, ['error_reporting=E_ALL', 'display_errors=1', 'html_errors=0']);
    $name = basename($script);

    Assert::assertSame(0, $exitCode, "Example {$name} exited with code {$exitCode}:\n{$output}");
    Assert::assertNotSame('', trim($output), "Example {$name} printed nothing");

    foreach (['Fatal error', 'Parse error', 'Uncaught', 'Warning:', 'Deprecated:', 'Notice:'] as $marker) {
        Assert::assertStringNotContainsString(
            $marker,
            $output,
            "Example {$name} emitted '{$marker}' in its output"
        );
    }
})->with(array_combine(
    array_map(fn (string $script) => basename($script), $exampleScripts),
    array_map(fn (string $script) => [$script], $exampleScripts)
));

// A new example must say what it demonstrates before it can ship, and a
// deleted one must not leave its assertions behind
it('has a demonstration for every example and none without a script', function () use ($demonstrations): void {
    expect(array_keys($demonstrations))->toBe(
        ExampleResults::names(),
        'Every numbered script in examples/ needs an entry in $demonstrations (tests/Feature/ExamplesTest.php) '
        . 'that asserts what the example is there to show, and every entry needs its script.'
    );
});

it('computes what it is there to demonstrate', function (string $example) use ($demonstrations): void {
    if (!isset($demonstrations[$example])) {
        Assert::fail(
            "examples/{$example}.php has no checked results. Add an entry for it to \$demonstrations in "
            . 'tests/Feature/ExamplesTest.php that asserts what the example is there to show.'
        );
    }

    $demonstrations[$example](ExampleResults::of($example));
})->with(ExampleResults::names());

it('has its results pinned by the golden test', function (string $example): void {
    expect(GoldenCases::all())->toHaveKey(GoldenCases::exampleFixture($example));
})->with(ExampleResults::names());

// Markup and styling are no part of what is pinned: a fixture holds results
// in fixture form, never a page and never the text an example prints
it('pins results, not the page or the printed text', function (string $example): void {
    $pinned = (string) file_get_contents(dirname(__DIR__) . '/Fixtures/golden/' . GoldenCases::exampleFixture($example));
    [, $printed] = runExampleScript(ExampleResults::directory() . "/{$example}.php", ['error_reporting=E_ALL', 'display_errors=1']);

    expect($pinned)->toStartWith("# The results of examples/{$example}.php");
    expect($pinned)->not->toBe($printed);
    foreach (['<html', '<section', '<h2>'] as $markup) {
        expect($pinned)->not->toContain($markup);
    }

    foreach (array_keys(ExampleResults::of($example)) as $name) {
        expect($pinned)->toContain("\n== {$name} ==\n");
    }
})->with(ExampleResults::names());

// Only a measured value may differ between runs, and the example must have
// said so. Everything else an example computes is the same every time: the
// script is run twice in surroundings chosen to differ (default timezone,
// float precision, locale variables in the environment, a working directory
// outside the repository) and must print the same text both times. PHP does
// not take its numeric locale from the environment unless a script calls
// setlocale(), so the locale variables only catch an example that does;
// the renderer is drawn under a decimal-comma locale in ExampleRendererTest.
// Gap left knowingly: one PHP version per run - the CI matrix (8.3, 8.4,
// 8.5) is what compares versions.
it('prints the same text whatever the timezone, locale, precision and working directory', function (string $example): void {
    $script = ExampleResults::directory() . "/{$example}.php";

    [$plainExit, $plain] = runExampleScript($script, ['error_reporting=-1', 'display_errors=1', 'html_errors=0']);
    [$otherExit, $other] = runExampleScript(
        $script,
        [
            'error_reporting=-1',
            'display_errors=1',
            'html_errors=0',
            'date.timezone=Pacific/Auckland',
            'precision=17',
            'serialize_precision=17',
        ],
        sys_get_temp_dir(),
        ['TZ' => 'Asia/Tokyo', 'LC_ALL' => 'de_DE.UTF-8', 'LANG' => 'de_DE.UTF-8']
    );

    expect($plainExit)->toBe(0)
        ->and($otherExit)->toBe(0);

    if (ExampleResults::containsMeasured(ExampleResults::of($example))) {
        // The measured figures differ by design; everything around them must not
        $withoutFigures = static fn (string $text): string => (string) preg_replace('/[\d.]+ (\w+) \(measured on this run\)/', '$1 (measured)', $text);

        expect($withoutFigures($other))->toBe($withoutFigures($plain))
            ->and($withoutFigures($plain))->not->toBe($plain);

        return;
    }

    expect($other)->toBe($plain);
})->with(ExampleResults::names());

it('draws every example as a page without losing a result', function (string $example): void {
    $results = ExampleResults::of($example);
    $html = Example::renderHtml('Title', 'Summary', $results, $example . '.php');

    expect($html)->toStartWith('<!DOCTYPE html>');
    foreach (array_keys($results) as $name) {
        expect($html)->toContain('<h2>' . htmlspecialchars($name, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</h2>');
    }
})->with(ExampleResults::names());

// An example is ordinary library usage that ends by handing over its
// results. One that printed or drew anything itself would be back to mixing
// what it computes with how it is displayed
it('leaves all display to the shared renderer', function (string $example): void {
    $source = (string) file_get_contents(ExampleResults::directory() . "/{$example}.php");

    expect($source)->toContain("require_once __DIR__ . '/support/Example.php';")
        ->toMatch('/\nreturn Example::present\(__FILE__, /');

    foreach ([
        'prints something itself' => '/\b(?:echo|print|printf|print_r|var_dump|var_export)\b/',
        'leaves PHP mode' => '/\?>/',
        'holds markup' => '/<(?:html|div|table|span|p|h\d)\b/i',
        // The suite includes every example in one process, where two functions of one name are fatal
        'declares a named function' => '/^\s*function\s+\w+\s*\(/m',
    ] as $problem => $pattern) {
        expect($source)->not->toMatch($pattern, "examples/{$example}.php {$problem}");
    }
})->with(ExampleResults::names());

/*
 * The index page and the examples README list the examples by hand, so both
 * can fall behind the directory. Each is compared with the scripts that
 * exist, in both directions.
 */
it('lists every example, and only examples that exist', function (string $listing): void {
    $text = (string) file_get_contents(ExampleResults::directory() . '/' . $listing);
    preg_match_all('/\b(\d\d-[a-z\d-]+)\.php\b/', $text, $matches);

    $listed = array_values(array_unique($matches[1]));
    sort($listed);

    $missing = array_values(array_diff(ExampleResults::names(), $listed));
    $absent = array_values(array_diff($listed, ExampleResults::names()));

    expect($missing)->toBe([], "examples/{$listing} does not list: " . implode(', ', $missing))
        ->and($absent)->toBe([], "examples/{$listing} lists scripts that do not exist: " . implode(', ', $absent));
})->with(['index.php', 'README.md']);

it('links every example from the index page and from the README table', function (): void {
    $index = runExampleScript(ExampleResults::directory() . '/index.php', ['error_reporting=E_ALL', 'display_errors=1'])[1];
    $readme = (string) file_get_contents(ExampleResults::directory() . '/README.md');

    foreach (ExampleResults::names() as $example) {
        expect($index)->toContain('<a href="' . $example . '.php">')
            ->and($readme)->toContain("| [{$example}.php]({$example}.php) | ");
    }

    expect(substr_count($index, '<a href="'))->toBe(count(ExampleResults::names()));
});

// A Schedule holds all of its events in memory, as an array: it is iterable
// and countable, and nothing is loaded lazily. The examples and the documents
// once said otherwise ("memory-efficient iteration", "count without loading"),
// which sent readers after a saving that does not exist. The phrases below
// are the ones those claims were made in; none may come back. The changelog
// is left out: it describes the old claim in order to record its removal.
it('does not claim that reading a schedule saves memory', function (string $file): void {
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/' . $file);
    Assert::assertNotSame('', $text, "{$file} is missing or empty");

    foreach ([
        '/memory[- ]efficien/i',
        '/without (?:loading|storing)/i',
        '/no memory load/i',
        '/lazy[- ](?:load|evaluat)/i',
        '/streaming-friendly/i',
        '/generator-based/i',
    ] as $claim) {
        Assert::assertDoesNotMatchRegularExpression(
            $claim,
            $text,
            "{$file} claims a memory saving a Schedule does not offer: its events are held in memory"
        );
    }
})->with([
    'README.md',
    'docs/USAGE.md',
    'docs/ARCHITECTURE.md',
    'examples/README.md',
    'examples/support/Example.php',
    ...array_map(fn (string $script) => 'examples/' . basename($script), $exampleScripts),
]);

// The library says participant. Sample data may be teams, clubs or players,
// but the prose of an example (its comments, its title and summary, the
// names of its results) and of the pages around it may not call the
// library's participants teams
it('says participant, not team, in the prose of the examples', function (string $file): void {
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/' . $file);

    // Sample data and the variables holding it: a quoted label, or a $teams list
    $prose = (string) preg_replace(['/\$\w*teams?\w*/i', "/'[^'\\n]*'\\s*(?:,|\\)|=>)/"], '', $text);
    $allowed = [
        // The examples README and index say what the sample data is
        'uses sports teams',
        // Example 14 and 15 are about a football tournament and a football league
        'six-team home-and-away league',
        "every team 48 hours' rest",
    ];

    expect(str_ireplace($allowed, '', $prose))->not->toMatch('/\bteams?\b/i');
})->with([
    'examples/README.md',
    'examples/support/Example.php',
    ...array_map(fn (string $script) => 'examples/' . basename($script), $exampleScripts),
]);

it('holds every event in memory, so iterating, counting and listing agree and repeat', function (): void {
    $schedule = (new RoundRobinScheduler())->schedule(array_map(
        fn (int $number) => new Participant("p{$number}", "Participant {$number}"),
        range(1, 6)
    ));

    $first = iterator_to_array($schedule);
    $second = iterator_to_array($schedule);

    // The same event objects on every pass: nothing is produced on demand
    expect($first)->toBe($schedule->getEvents())
        ->and($second)->toBe($first)
        ->and(count($schedule))->toBe(15)
        ->and(array_merge(...array_values($schedule->getEventsByRound())))->toBe($first);
});
