<?php

declare(strict_types=1);

use MissionGaming\Tactician\Tests\Support\GoldenCases;
use PHPUnit\Framework\Assert;

// Examples are executable documentation and must not ship without validation.
// This test auto-discovers every script in examples/, so a new example is
// covered the moment it is added: each script must run cleanly under full
// error reporting. Stale examples have shipped fatal errors before - see the
// git history for examples 07, 09, and 11.
//
// Running cleanly is not the same as printing the right thing, so the
// examples that print plain text also have their exact output pinned as
// golden files (GoldenCases::PLAIN_TEXT_EXAMPLES, compared by
// tests/Feature/GoldenOutputTest.php, regenerated by `composer golden-update`).
// This test makes that list complete: a plain-text example that is not on it
// fails here.
//
// Gap left knowingly: the HTML examples (01 to 12 and index.php) are only
// run, not pinned. They are pages for a browser, and several print measured
// timings and memory figures that differ on every run.

$exampleScripts = glob(dirname(__DIR__, 2) . '/examples/*.php') ?: [];

it('discovers example scripts to validate', function () use ($exampleScripts): void {
    expect($exampleScripts)->not->toBeEmpty();
});

it('runs cleanly under full error reporting', function (string $script): void {
    $command = sprintf(
        '%s -d error_reporting=E_ALL -d display_errors=1 %s 2>&1',
        escapeshellarg(PHP_BINARY),
        escapeshellarg($script)
    );

    exec($command, $outputLines, $exitCode);
    $output = implode("\n", $outputLines);
    $name = basename($script);

    Assert::assertSame(0, $exitCode, "Example {$name} exited with code {$exitCode}:\n{$output}");

    foreach (['Fatal error', 'Parse error', 'Uncaught', 'Warning:', 'Deprecated:', 'Notice:'] as $marker) {
        Assert::assertStringNotContainsString(
            $marker,
            $output,
            "Example {$name} emitted '{$marker}' in its output"
        );
    }

    if (!str_contains($output, '<html')) {
        Assert::assertContains(
            basename($script, '.php'),
            GoldenCases::PLAIN_TEXT_EXAMPLES,
            "Example {$name} prints plain text, so its output must be pinned: add it to "
            . 'GoldenCases::PLAIN_TEXT_EXAMPLES (and to the matrix in GoldenOutputTest), '
            . 'run `composer golden-update`, and review the new fixture.'
        );
    }
})->with(array_combine(
    array_map(fn (string $script) => basename($script), $exampleScripts),
    array_map(fn (string $script) => [$script], $exampleScripts)
));

it('pins only examples that exist and print plain text', function (string $example) use ($exampleScripts): void {
    $script = dirname(__DIR__, 2) . '/examples/' . $example . '.php';

    $pinned = (string) file_get_contents(dirname(__DIR__) . '/Fixtures/golden/' . GoldenCases::exampleFixture($example));

    expect($exampleScripts)->toContain($script);
    expect($pinned)->not->toBe('');
    expect($pinned)->not->toContain('<html');
})->with(GoldenCases::PLAIN_TEXT_EXAMPLES);

// A Schedule holds all of its events in memory, as an array: it is iterable
// and countable, and nothing is loaded lazily. The examples and the documents
// once said otherwise ("memory-efficient iteration", "count without loading"),
// which sent readers after a saving that does not exist. The phrases below
// are the ones those claims were made in; none may come back. The changelog
// and the memory bank are left out: they describe the old claim in order to
// record its removal.
it('does not claim that reading a schedule saves memory', function (string $file): void {
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/' . $file);
    Assert::assertNotSame('', $text, "{$file} is missing or empty");

    foreach ([
        '/memory[- ]efficien/i',
        '/without (?:loading|storing)/i',
        '/no memory load/i',
        '/lazy[- ](?:load|evaluat)/i',
        '/streaming-friendly/i',
        '/generator-based/i',
    ] as $claim) {
        Assert::assertDoesNotMatchRegularExpression(
            $claim,
            $text,
            "{$file} claims a memory saving a Schedule does not offer: its events are held in memory"
        );
    }
})->with([
    'README.md',
    'docs/USAGE.md',
    'docs/ARCHITECTURE.md',
    'examples/README.md',
    ...array_map(fn (string $script) => 'examples/' . basename($script), $exampleScripts),
]);

it('holds every event in memory, so iterating, counting and listing agree and repeat', function (): void {
    $schedule = (new MissionGaming\Tactician\Scheduling\RoundRobinScheduler())->schedule(array_map(
        fn (int $number) => new MissionGaming\Tactician\DTO\Participant("p{$number}", "Participant {$number}"),
        range(1, 6)
    ));

    $first = iterator_to_array($schedule);
    $second = iterator_to_array($schedule);

    // The same event objects on every pass: nothing is produced on demand
    expect($first)->toBe($schedule->getEvents())
        ->and($second)->toBe($first)
        ->and(count($schedule))->toBe(15)
        ->and(array_merge(...array_values($schedule->getEventsByRound())))->toBe($first);
});

// A pinned example must print the same bytes wherever it runs, or its golden
// file fails on the next machine for no reason a reviewer can act on. Each
// script is run here in surroundings chosen to differ from the ones the
// fixture was written in: another default timezone, another float precision,
// a locale with a decimal comma, and a working directory outside the
// repository. Gap left knowingly: one PHP version per run - the CI matrix
// (8.3, 8.4, 8.5) is what compares versions.
it('prints the pinned output whatever the timezone, locale, precision and working directory', function (string $example): void {
    $root = dirname(__DIR__, 2);
    $captured = tempnam(sys_get_temp_dir(), 'example');
    if ($captured === false) {
        Assert::fail('Could not create a temporary file in ' . sys_get_temp_dir());
    }

    // Both streams append to one file, as they do when the fixture is written
    $process = proc_open(
        [
            PHP_BINARY,
            '-d', 'error_reporting=-1',
            '-d', 'display_errors=1',
            '-d', 'html_errors=0',
            '-d', 'date.timezone=Pacific/Auckland',
            '-d', 'precision=17',
            '-d', 'serialize_precision=17',
            $root . '/examples/' . $example . '.php',
        ],
        [1 => ['file', $captured, 'a'], 2 => ['file', $captured, 'a']],
        $pipes,
        sys_get_temp_dir(),
        ['TZ' => 'Asia/Tokyo', 'LC_ALL' => 'de_DE.UTF-8', 'LANG' => 'de_DE.UTF-8']
    );
    if ($process === false) {
        unlink($captured);
        Assert::fail("Could not start PHP to run examples/{$example}.php");
    }

    $exitCode = proc_close($process);
    $output = (string) file_get_contents($captured);
    unlink($captured);

    expect($exitCode)->toBe(0)
        ->and($output)->toBe((string) file_get_contents($root . '/tests/Fixtures/golden/' . GoldenCases::exampleFixture($example)));
})->with(GoldenCases::PLAIN_TEXT_EXAMPLES);
