<?php

declare(strict_types=1);

use MissionGaming\Tactician\Tests\Support\GoldenCases;
use PHPUnit\Framework\Assert;

// Examples are executable documentation and must not ship without validation.
// This test auto-discovers every script in examples/, so a new example is
// covered the moment it is added: each script must run cleanly under full
// error reporting. Stale examples have shipped fatal errors before - see the
// git history for examples 07, 09, and 11.
//
// Running cleanly is not the same as printing the right thing, so the
// examples that print plain text also have their exact output pinned as
// golden files (GoldenCases::PLAIN_TEXT_EXAMPLES, compared by
// tests/Feature/GoldenOutputTest.php, regenerated by `composer golden-update`).
// This test makes that list complete: a plain-text example that is not on it
// fails here.
//
// Gap left knowingly: the HTML examples (01 to 12 and index.php) are only
// run, not pinned. They are pages for a browser, and several print measured
// timings and memory figures that differ on every run.

$exampleScripts = glob(dirname(__DIR__, 2) . '/examples/*.php') ?: [];

it('discovers example scripts to validate', function () use ($exampleScripts): void {
    expect($exampleScripts)->not->toBeEmpty();
});

it('runs cleanly under full error reporting', function (string $script): void {
    $command = sprintf(
        '%s -d error_reporting=E_ALL -d display_errors=1 %s 2>&1',
        escapeshellarg(PHP_BINARY),
        escapeshellarg($script)
    );

    exec($command, $outputLines, $exitCode);
    $output = implode("\n", $outputLines);
    $name = basename($script);

    Assert::assertSame(0, $exitCode, "Example {$name} exited with code {$exitCode}:\n{$output}");

    foreach (['Fatal error', 'Parse error', 'Uncaught', 'Warning:', 'Deprecated:', 'Notice:'] as $marker) {
        Assert::assertStringNotContainsString(
            $marker,
            $output,
            "Example {$name} emitted '{$marker}' in its output"
        );
    }

    if (!str_contains($output, '<html')) {
        Assert::assertContains(
            basename($script, '.php'),
            GoldenCases::PLAIN_TEXT_EXAMPLES,
            "Example {$name} prints plain text, so its output must be pinned: add it to "
            . 'GoldenCases::PLAIN_TEXT_EXAMPLES (and to the matrix in GoldenOutputTest), '
            . 'run `composer golden-update`, and review the new fixture.'
        );
    }
})->with(array_combine(
    array_map(fn (string $script) => basename($script), $exampleScripts),
    array_map(fn (string $script) => [$script], $exampleScripts)
));

it('pins only examples that exist and print plain text', function (string $example) use ($exampleScripts): void {
    $script = dirname(__DIR__, 2) . '/examples/' . $example . '.php';

    $pinned = (string) file_get_contents(dirname(__DIR__) . '/Fixtures/golden/' . GoldenCases::exampleFixture($example));

    expect($exampleScripts)->toContain($script);
    expect($pinned)->not->toBe('');
    expect($pinned)->not->toContain('<html');
})->with(GoldenCases::PLAIN_TEXT_EXAMPLES);

// A Schedule holds all of its events in memory, as an array: it is iterable
// and countable, and nothing is loaded lazily. The examples and the documents
// once said otherwise ("memory-efficient iteration", "count without loading"),
// which sent readers after a saving that does not exist. The phrases below
// are the ones those claims were made in; none may come back. The changelog
// is left out: it describes the old claim in order to record its removal.
it('does not claim that reading a schedule saves memory', function (string $file): void {
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/' . $file);
    Assert::assertNotSame('', $text, "{$file} is missing or empty");

    foreach ([
        '/memory[- ]efficien/i',
        '/without (?:loading|storing)/i',
        '/no memory load/i',
        '/lazy[- ](?:load|evaluat)/i',
        '/streaming-friendly/i',
        '/generator-based/i',
    ] as $claim) {
        Assert::assertDoesNotMatchRegularExpression(
            $claim,
            $text,
            "{$file} claims a memory saving a Schedule does not offer: its events are held in memory"
        );
    }
})->with([
    'README.md',
    'docs/USAGE.md',
    'docs/ARCHITECTURE.md',
    'examples/README.md',
    ...array_map(fn (string $script) => 'examples/' . basename($script), $exampleScripts),
]);

it('holds every event in memory, so iterating, counting and listing agree and repeat', function (): void {
    $schedule = (new MissionGaming\Tactician\Scheduling\RoundRobinScheduler())->schedule(array_map(
        fn (int $number) => new MissionGaming\Tactician\DTO\Participant("p{$number}", "Participant {$number}"),
        range(1, 6)
    ));

    $first = iterator_to_array($schedule);
    $second = iterator_to_array($schedule);

    // The same event objects on every pass: nothing is produced on demand
    expect($first)->toBe($schedule->getEvents())
        ->and($second)->toBe($first)
        ->and(count($schedule))->toBe(15)
        ->and(array_merge(...array_values($schedule->getEventsByRound())))->toBe($first);
});

// A pinned example must print the same bytes wherever it runs, or its golden
// file fails on the next machine for no reason a reviewer can act on. Each
// script is run here in surroundings chosen to differ from the ones the
// fixture was written in: another default timezone, another float precision,
// a locale with a decimal comma, and a working directory outside the
// repository. Gap left knowingly: one PHP version per run - the CI matrix
// (8.3, 8.4, 8.5) is what compares versions.
it('prints the pinned output whatever the timezone, locale, precision and working directory', function (string $example): void {
    $root = dirname(__DIR__, 2);
    $captured = tempnam(sys_get_temp_dir(), 'example');
    if ($captured === false) {
        Assert::fail('Could not create a temporary file in ' . sys_get_temp_dir());
    }

    // Both streams append to one file, as they do when the fixture is written
    $process = proc_open(
        [
            PHP_BINARY,
            '-d', 'error_reporting=-1',
            '-d', 'display_errors=1',
            '-d', 'html_errors=0',
            '-d', 'date.timezone=Pacific/Auckland',
            '-d', 'precision=17',
            '-d', 'serialize_precision=17',
            $root . '/examples/' . $example . '.php',
        ],
        [1 => ['file', $captured, 'a'], 2 => ['file', $captured, 'a']],
        $pipes,
        sys_get_temp_dir(),
        ['TZ' => 'Asia/Tokyo', 'LC_ALL' => 'de_DE.UTF-8', 'LANG' => 'de_DE.UTF-8']
    );
    if ($process === false) {
        unlink($captured);
        Assert::fail("Could not start PHP to run examples/{$example}.php");
    }

    $exitCode = proc_close($process);
    $output = (string) file_get_contents($captured);
    unlink($captured);

    expect($exitCode)->toBe(0)
        ->and($output)->toBe((string) file_get_contents($root . '/tests/Fixtures/golden/' . GoldenCases::exampleFixture($example)));
})->with(GoldenCases::PLAIN_TEXT_EXAMPLES);

// `composer examples` (the last step of `composer ci`) is tests/bin/run-examples.php.
// The runner is pointed here at throwaway directories, so that its failure
// paths are exercised without breaking a real example. Gap left knowingly:
// the runner is not run over the real examples/ in this file - the gate does
// that, and the test above already runs every real example.
$runExamples = function (array $scripts, bool $createDirectory = true): array {
    $directory = sys_get_temp_dir() . '/run-examples-' . bin2hex(random_bytes(6));

    if ($createDirectory && !mkdir($directory)) {
        Assert::fail("Could not create {$directory}");
    }

    foreach ($scripts as $name => $source) {
        file_put_contents($directory . '/' . $name, $source);
    }

    try {
        $process = proc_open(
            [PHP_BINARY, dirname(__DIR__) . '/bin/run-examples.php', $directory],
            [1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
            $pipes
        );
        if ($process === false) {
            Assert::fail('Could not start PHP to run tests/bin/run-examples.php');
        }

        $stdout = (string) stream_get_contents($pipes[1]);
        $stderr = (string) stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        $ran = is_file($directory . '/ran.log')
            ? file($directory . '/ran.log', FILE_IGNORE_NEW_LINES) ?: []
            : [];
    } finally {
        foreach (glob($directory . '/*') ?: [] as $file) {
            unlink($file);
        }
        if (is_dir($directory)) {
            rmdir($directory);
        }
    }

    return ['exitCode' => $exitCode, 'stdout' => $stdout, 'stderr' => $stderr, 'ran' => $ran];
};

// Each throwaway script records that it ran, prints to standard output, and
// exits with the given code
$exampleSource = fn (string $label, int $exitCode = 0): string => sprintf(
    "<?php\nfile_put_contents(__DIR__ . '/ran.log', %s . \"\\n\", FILE_APPEND);\necho %s;\nexit(%d);\n",
    var_export($label, true),
    var_export("output of {$label}\n", true),
    $exitCode
);

it('wires `composer examples` and the gate to the example runner', function (): void {
    $composer = json_decode((string) file_get_contents(dirname(__DIR__, 2) . '/composer.json'), true);

    /** @var array{scripts: array<string, string|list<string>>} $composer */
    expect($composer['scripts']['examples'])->toBe('@php tests/bin/run-examples.php')
        ->and($composer['scripts']['ci'])->toContain('@examples')
        ->and(is_file(dirname(__DIR__) . '/bin/run-examples.php'))->toBeTrue();
});

it('runs every script of the directory, in name order, and prints nothing when all succeed', function () use ($runExamples, $exampleSource): void {
    $result = $runExamples([
        '02-second.php' => $exampleSource('second'),
        '10-third.php' => $exampleSource('third'),
        '01-first.php' => $exampleSource('first'),
        // Not a script: only *.php files are examples
        'README.md' => 'not PHP',
    ]);

    expect($result)->toBe([
        'exitCode' => 0,
        'stdout' => '',
        'stderr' => '',
        'ran' => ['first', 'second', 'third'],
    ]);
});

it('fails on the first script that exits non-zero, names it, shows its output, and runs no further script', function () use ($runExamples, $exampleSource): void {
    $result = $runExamples([
        '01-first.php' => $exampleSource('first'),
        '02-broken.php' => $exampleSource('broken', 3),
        '03-never.php' => $exampleSource('never'),
    ]);

    expect($result['exitCode'])->toBe(1)
        ->and($result['ran'])->toBe(['first', 'broken'])
        ->and($result['stdout'])->toBe('')
        // The output of the script that failed, and of no other
        ->and($result['stderr'])->toBe("output of broken\nExample 02-broken.php exited with code 3.\n");
});

it('fails when the last script is the one that exits non-zero', function () use ($runExamples, $exampleSource): void {
    $result = $runExamples([
        '01-first.php' => $exampleSource('first'),
        '02-broken.php' => $exampleSource('broken', 255),
    ]);

    expect($result['exitCode'])->toBe(1)
        ->and($result['ran'])->toBe(['first', 'broken'])
        ->and($result['stderr'])->toContain('Example 02-broken.php exited with code 255.');
});

it('states the reason when a script dies of an uncaught exception', function () use ($runExamples): void {
    // The configuration under which PHP prints the error to standard output
    // only, which is the stream the runner captures: PHP with no php.ini
    // behaves this way
    $result = $runExamples([
        '01-throws.php' => "<?php\nini_set('display_errors', '1');\nini_set('log_errors', '0');\n"
            . "throw new RuntimeException('the reason');\n",
    ]);

    expect($result['exitCode'])->toBe(1)
        ->and($result['stderr'])->toContain('the reason')
        ->toContain('Example 01-throws.php exited with code 255.');
});

it('fails a script that does not parse', function () use ($runExamples): void {
    $result = $runExamples(['01-broken.php' => "<?php\nthis is not PHP\n"]);

    expect($result['exitCode'])->toBe(1)
        ->and($result['stderr'])->toContain('Example 01-broken.php exited with code 255.');
});

// PHP exits with 0 after a warning, a notice or a deprecation, so the exit
// code alone would let one through. The runner reports every level on
// standard error and fails on anything written there.
it('fails a script that exits zero after a diagnostic, names it, shows the diagnostic, and runs no further script', function (string $statement, string $expected) use ($runExamples, $exampleSource): void {
    $result = $runExamples([
        '01-first.php' => $exampleSource('first'),
        '02-noisy.php' => "<?php\nfile_put_contents(__DIR__ . '/ran.log', \"noisy\\n\", FILE_APPEND);\n{$statement}\necho \"output of noisy\\n\";\n",
        '03-never.php' => $exampleSource('never'),
    ]);

    expect($result['exitCode'])->toBe(1)
        ->and($result['ran'])->toBe(['first', 'noisy'])
        ->and($result['stdout'])->toBe('')
        ->and($result['stderr'])->toContain($expected)
        ->toContain("output of noisy\n")
        ->toEndWith("Example 02-noisy.php wrote to standard error.\n");
})->with([
    'a warning' => ['$list = []; echo $list["missing"];', 'Undefined array key "missing"'],
    'a warning from a variable never set' => ['echo $neverSet;', 'Undefined variable $neverSet'],
    'a deprecation' => ['trigger_error("old call", E_USER_DEPRECATED);', 'old call'],
    'a notice' => ['trigger_error("take note", E_USER_NOTICE);', 'take note'],
    'a warning the script raises itself' => ['trigger_error("raised by hand", E_USER_WARNING);', 'raised by hand'],
    'a direct write to standard error' => ['fwrite(STDERR, "written by hand\n");', 'written by hand'],
]);

it('does not fail a script whose standard output merely mentions a warning', function () use ($runExamples): void {
    $result = $runExamples(['01-talks.php' => "<?php\necho \"Warning: this text is ordinary output\\n\";\n"]);

    expect($result)->toBe(['exitCode' => 0, 'stdout' => '', 'stderr' => '', 'ran' => []]);
});

// An empty run must not pass for a green one: a wrong path or a renamed
// directory would otherwise turn the smoke-run into a check of nothing.
it('fails when the directory holds no script', function (array $files, bool $createDirectory) use ($runExamples): void {
    $result = $runExamples($files, $createDirectory);

    expect($result['exitCode'])->toBe(1)
        ->and($result['stdout'])->toBe('')
        ->and($result['stderr'])->toStartWith('No example scripts found in ')
        ->and($result['ran'])->toBe([]);
})->with([
    'an empty directory' => [[], true],
    'a directory with no PHP file' => [['README.md' => 'not PHP'], true],
    'a directory that does not exist' => [[], false],
]);
